"""
Django settings for UHLDOCUMENT project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v7&becjbm=37*$m8qqw78_r-&p&xdyl(vx=m)q0geh$@r1m0pi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'backend',
    'tinymce',
    'ckeditor',
    'ckeditor_uploader',
    'backend.templatetags',
    
]

INSTALLED_APPS = INSTALLED_APPS + EXTERNAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'backend.middleware.CurrentUserMiddleware',  # Thay your_app_name bằng tên ứng dụng của bạn
    'backend.middleware.WarningMiddleware',
    'backend.middleware.SaveIPAddressMiddleware',
    'backend.middleware.CustomPermissionDeniedMiddleware',
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'UHLDOCUMENT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend.context_processors.menu_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'UHLDOCUMENT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'uhldocu',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os.path
from pathlib import Path
import os 
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload')
MEDIA_URL = '/upload/'


# Thêm cài đặt CKEditor
CKEDITOR_UPLOAD_PATH = 'content/ckeditor/'


from ckeditor.configs import DEFAULT_CONFIG
CKEDITOR_UPLOAD_PATH = 'media/upload'
CKEDITOR_IMAGE_BACKEND = 'pillow'
# CKEDITOR_THUMBNAIL_SIZE = (300, 300)
CKEDITOR_IMAGE_QUALITY = 40
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_ALLOW_NONIMAGE_FILES = True


CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'width': '840px',  
        'height': '600px', 
        'toolbar': 'full',
        'toolbarGroups': None,
        'extraPlugins': ','.join(["image2", "codesnippet"]),
        'removePlugins': ','.join(["image"]),  # Fix the typo here
        'codeSnippet_theme': 'xcode',
    },
}


# Cài đặt thời gian sống của cookie phiên là 1 giờ (3600 giây)
SESSION_COOKIE_AGE = 3600

# Lưu lại phiên sau mỗi request
SESSION_SAVE_EVERY_REQUEST = True 

LANGUAGE_CODE = 'vi'

LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = 'home'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # Cổng SMTP (thông thường là 587 cho TLS hoặc 465 cho SSL)
EMAIL_USE_TLS = True  # Sử dụng TLS để bảo mật kết nối
EMAIL_HOST_USER = 'tranthanh0898256009@gmail.com'  # Tài khoản email
EMAIL_HOST_PASSWORD = 'beeohogyjuzrymcf'  # Mật khẩu email



