# Generated by Django 5.0 on 2024-01-28 08:06

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mức độ văn bản',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Loại văn bản',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên trạng thái')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name_plural': 'Trạng thái xử lý văn bản',
            },
        ),
        migrations.CreateModel(
            name='uploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(null=True, verbose_name='Tuần')),
                ('year', models.PositiveIntegerField(default=2024, null=True, verbose_name='Năm')),
                ('start_date', models.DateField(null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(null=True, verbose_name='Ngày kết thúc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name_plural': 'Tuần',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('status', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Thông báo',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department_works_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.position')),
            ],
        ),
        migrations.CreateModel(
            name='ReadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveIntegerField(default=1)),
                ('first_read_time', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lượt đọc',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by_users',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', through='backend.ReadRecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tiêu đề công việc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả công việc')),
                ('image', models.ImageField(blank=True, null=True, upload_to='task/')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Chưa hoạt động'), (2, 'Đang hoạt động'), (3, 'Hoàn thành'), (4, 'Quá hạn')], default=1, verbose_name='Trạng thái công việc')),
                ('sum_progress', models.PositiveIntegerField(default=0, verbose_name='Tổng tiến độ')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(choices=[(1, 'Bình thường'), (2, 'Thấp'), (3, 'Cao'), (4, 'Khẩn cấp'), (5, 'Quan trọng'), (6, 'Xem xét'), (7, 'Tự do')], default=1, verbose_name='Độ ưu tiên')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người được giao')),
                ('confirmed_users', models.ManyToManyField(blank=True, related_name='confirmed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người đã xác nhận tham gia công việc')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name_plural': 'Công việc',
            },
        ),
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Trích yêu')),
                ('origin', models.CharField(max_length=255, null=True, verbose_name='Nguồn gốc')),
                ('number', models.CharField(max_length=255, null=True, verbose_name='Số hiệu')),
                ('publication_date', models.DateField(null=True, verbose_name='Ngày tạo gốc')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Tạo ngày')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Cập nhật ngày')),
                ('description', models.TextField(null=True, verbose_name='Mô tả')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_template_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.documenttype', verbose_name='Loại văn bản')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.documentlevel', verbose_name='Mức độ văn bản')),
                ('uploadfile', models.ManyToManyField(to='backend.uploadfile', verbose_name='File đính kèm')),
            ],
            options={
                'verbose_name_plural': 'Văn bản mẫu',
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Phần trăm tiến độ')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='Ngày cập nhật')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='backend.task', verbose_name='Công việc')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật tiến độ')),
                ('fileupdate', models.ManyToManyField(blank=True, to='backend.uploadfile', verbose_name='Files đính kèm')),
            ],
            options={
                'verbose_name_plural': 'Tiền độ công việc',
            },
        ),
        migrations.CreateModel(
            name='OutgoingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=255, verbose_name='Số ký hiệu')),
                ('receipt_date', models.DateField(null=True, verbose_name='Ngày nhận văn bản')),
                ('issuance_date', models.DateField(null=True, verbose_name='Ngày ban hành văn bản')),
                ('current_number', models.CharField(max_length=255, null=True, verbose_name='Số hiện tại')),
                ('arrival_number', models.CharField(max_length=255, null=True, verbose_name='Số đến')),
                ('summary', models.TextField(verbose_name='Trích yếu')),
                ('advisory_opinions', models.TextField(null=True, verbose_name='Ý kiến tham mưu')),
                ('publish', models.BooleanField(default=True, verbose_name='Trạng thái lưu hành')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Tạo ngày')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Cập nhật ngày')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.documenttype', verbose_name='Loại văn bản')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.documentlevel', verbose_name='Mức độ văn bản')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.processstatus', verbose_name='Trạng thái xử lý')),
                ('uploadfile', models.ManyToManyField(blank=True, to='backend.uploadfile', verbose_name='File đính kèm')),
            ],
            options={
                'verbose_name_plural': 'Văn bản đi',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='uploadfile',
            field=models.ManyToManyField(blank=True, to='backend.uploadfile'),
        ),
        migrations.CreateModel(
            name='IncomingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_agency', models.CharField(max_length=255, verbose_name='Cơ quan pháp hành')),
                ('responsible_agency', models.CharField(max_length=255, null=True, verbose_name='Cơ quan chủ quản')),
                ('reference_number', models.CharField(max_length=255, verbose_name='Số ký hiệu')),
                ('receipt_date', models.DateField(null=True, verbose_name='Ngày nhận văn bản')),
                ('issuance_date', models.DateField(null=True, verbose_name='Ngày ban hành văn bản')),
                ('current_number', models.CharField(max_length=255, null=True, verbose_name='Số hiện tại')),
                ('arrival_number', models.CharField(max_length=255, null=True, verbose_name='Số đến')),
                ('summary', models.TextField(verbose_name='Trích yếu')),
                ('advisory_opinions', models.TextField(null=True, verbose_name='Ý kiến tham mưu')),
                ('publish', models.BooleanField(default=True, verbose_name='Trạng thái lưu hành')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Tạo ngày')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Cập nhật ngày')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.documenttype', verbose_name='Loại văn bản')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.documentlevel', verbose_name='Mức độ văn bản')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.processstatus', verbose_name='Trạng thái xử lý')),
                ('uploadfile', models.ManyToManyField(blank=True, to='backend.uploadfile', verbose_name='File đính kèm')),
            ],
            options={
                'verbose_name_plural': 'Văn bản đến',
            },
        ),
        migrations.CreateModel(
            name='uploadFileTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='task_files/')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadfiles_task', to='backend.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='uploadfiles',
            field=models.ManyToManyField(blank=True, related_name='task_uploadfiles', to='backend.uploadfiletask', verbose_name='file đính kèm'),
        ),
        migrations.CreateModel(
            name='UserConfirmationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên hoạt động')),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_category', models.IntegerField(choices=[(1, 'Lịch trường'), (2, 'Lịch phòng ban'), (3, 'Lịch lãnh đạo'), (4, 'Lịch cá nhân')], default=1, verbose_name='Loại lịch công tác')),
                ('work_date', models.DateField(verbose_name='Ngày làm việc')),
                ('morning_or_afternoon', models.BooleanField(choices=[(True, 'Buổi sáng'), (False, 'Buổi chiều')], default=True, verbose_name='Buổi sáng hoặc buổi chiều')),
                ('start_time', models.TimeField(null=True, verbose_name='Thời gian bắt đầu')),
                ('end_time', models.TimeField(null=True, verbose_name='Thời gian kết thúc')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Địa điểm')),
                ('leading_official', models.CharField(max_length=255, null=True, verbose_name='Người lãnh đạo')),
                ('participants', models.TextField(null=True, verbose_name='Thành phần tham gia')),
                ('preparation', models.TextField(null=True, verbose_name='Chuẩn bị')),
                ('content', models.TextField(null=True, verbose_name='Nội dung')),
                ('description', models.TextField(null=True, verbose_name='Ghi chú')),
                ('status', models.BooleanField(choices=[(True, 'Hoàn thành'), (False, 'Chưa hoàn thành')], default=False, verbose_name='Trạng thái')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Tạo ngày')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Cập nhật ngày')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('department', models.ManyToManyField(blank=True, to='backend.department', verbose_name='Phòng ban')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.week', verbose_name='Tuần thứ')),
            ],
            options={
                'verbose_name_plural': 'Lịch công tác',
            },
        ),
    ]
