# Generated by Django 5.0 on 2024-01-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='uploadfiles',
        ),
        migrations.AddField(
            model_name='task',
            name='taskfiles',
            field=models.ManyToManyField(blank=True, related_name='task_uploadfiles', to='backend.uploadfiletask', verbose_name='file đã giao'),
        ),
    ]
