# Generated by Django 5.0 on 2024-01-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_uploadfiletask_upload_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfiletask',
            options={'verbose_name_plural': 'Tệp tin công việc'},
        ),
    ]
