# Generated by Django 5.0 on 2024-01-29 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_catagorynotification_options_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_comments', to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.AddField(
            model_name='notification',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments_notification', to='backend.comment', verbose_name='bình luận'),
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments_task', to='backend.comment', verbose_name='bình luận'),
        ),
    ]
