# Generated by Django 5.0 on 2024-01-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_comment_user_remove_notification_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_original_content',
            new_name='original_content',
        ),
    ]
