# Generated by Django 5.0 on 2024-01-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename__original_content_comment_original_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
