# Generated by Django 5.0 on 2024-01-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'UnActive')], default=True, verbose_name='Trạng thái'),
        ),
    ]
