# Generated by Django 5.0 on 2024-01-31 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_comment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Tài khoản'},
        ),
        migrations.AddField(
            model_name='account',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Căn cước công dân'),
        ),
        migrations.AddField(
            model_name='account',
            name='citizen_id_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cấp căn cước công dân'),
        ),
        migrations.AddField(
            model_name='account',
            name='citizen_id_issuing_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nơi cấp căn cước công dân'),
        ),
        migrations.AddField(
            model_name='account',
            name='current_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Công ty hiện đang làm việc'),
        ),
        migrations.AddField(
            model_name='account',
            name='educational_background',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trình độ văn hóa'),
        ),
        migrations.AddField(
            model_name='account',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dân tộc'),
        ),
        migrations.AddField(
            model_name='account',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Giới thiệu bản thân'),
        ),
        migrations.AddField(
            model_name='account',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quốc tịch'),
        ),
        migrations.AddField(
            model_name='account',
            name='office_address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ cơ quan'),
        ),
        migrations.AddField(
            model_name='account',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại cơ quan'),
        ),
        migrations.AddField(
            model_name='account',
            name='professional_degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trình độ chuyên môn'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='account',
            name='department_works_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.department', verbose_name='Bộ phận làm việc'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Nam'), (False, 'Nữ')], default=True, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.position', verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.CreateModel(
            name='CitizenIDImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='citizen_id_images/', verbose_name='Hình ảnh căn cước công dân')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_id_image', to='backend.account', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hình ảnh căn cước công dân',
                'verbose_name_plural': 'Hình ảnh căn cước công dân',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='itizen_id_images',
            field=models.ManyToManyField(blank=True, related_name='citizen_id_images', to='backend.citizenidimage', verbose_name='Hình ảnh căn cước công dân'),
        ),
    ]
