# Generated by Django 5.0 on 2024-01-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_account_options_account_citizen_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizenidimage',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='link_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Link Facebook'),
        ),
        migrations.AddField(
            model_name='account',
            name='link_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Link Instagram'),
        ),
        migrations.AddField(
            model_name='account',
            name='link_zalo',
            field=models.URLField(blank=True, null=True, verbose_name='Link Zalo'),
        ),
    ]
