# Generated by Django 5.0 on 2024-01-31 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_citizenidimage_account_account_link_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Dân tộc')),
            ],
            options={
                'verbose_name': 'Dân tộc',
                'verbose_name_plural': 'Dân tộc',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ethnicity', verbose_name='Dân tộc'),
        ),
    ]
