# Generated by Django 5.0 on 2024-02-03 03:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_nationality_alter_account_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='itizen_id_images',
            new_name='citizen_id_images',
        ),
        migrations.AlterField(
            model_name='account',
            name='introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Giới thiệu bản thân'),
        ),
    ]
