# Generated by Django 5.0 on 2024-02-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_itizen_id_images_account_citizen_id_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
    ]
