# Generated by Django 5.0 on 2024-02-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_account_introduction_alter_account_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenidimage',
            name='image',
            field=models.FileField(null=True, upload_to='citizen_id_images/', verbose_name='Hình ảnh căn cước công dân'),
        ),
    ]
